[package]
name = "sutombot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.5"
# tokio = "1.26.0"
tokio = { features=["rt-multi-thread"], version = "1.26.0" }
dotenv = "0.15.0"